In [67]:
import time
import requests
import pandas as pd
import csv

In [100]:
HEADERS = {"User-Agent": "BookDatasetBuilder/1.0 (contact: you@example.com)"}

# Mapea la lista de géneros -> el "subject" que usa Open Library en la URL.

GENRE_TO_SUBJECT = {
    "Fantasy": "fantasy",
    "Science fiction": "science_fiction",
    "Mystery": "mystery",
    "Romance": "romance",
    "Horror": "horror",
    "Historical fiction": "historical_fiction",
    "Young adult": "young_adult",
    "Non fiction": "nonfiction",
}

def fetch_subject_works(subject_slug: str, limit: int = 200, sleep_s: float = 0.2) -> list[dict]:
    """
    Open Library Subjects API:
    GET /subjects/{subject}.json?limit=...
    Devuelve obras asociadas al subject.  :contentReference[oaicite:1]{index=1}
    """
    url = f"https://openlibrary.org/subjects/{subject_slug}.json"
    params = {"limit": limit, "details": "true"}  # details añade info útil cuando esté disponible
    r = requests.get(url, params=params, headers=HEADERS, timeout=30)
    r.raise_for_status()
    data = r.json()
    time.sleep(sleep_s)
    return data.get("works", [])

def best_year(work: dict):
    # subjects API suele traer first_publish_year o first_publish_date
    y = work.get("first_publish_year")
    if isinstance(y, int):
        return y
    d = work.get("first_publish_date")
    if isinstance(d, str) and len(d) >= 4 and d[:4].isdigit():
        return int(d[:4])
    return None

def best_author(work: dict):
    authors = work.get("authors") or []
    if authors and isinstance(authors, list):
        name = authors[0].get("name")
        return name
    return None


def f_synopsis(work_key: str, sleep_s: float = 1, delay: int = 4):
    """
    Obtiene la sinopsis (description) desde el endpoint de la obra:
    https://openlibrary.org{work_key}.json

    Nota: 'description' puede venir como string o como dict {'value': '...'}.
    """
    if not work_key:
        return None

    url = f"https://openlibrary.org{work_key}.json"
    
    while True:
        try:
            r = requests.get(url, headers=HEADERS, timeout=30)
            r.raise_for_status()
            data = r.json()

            description = data.get("description")
            if isinstance(description, str):
                synopsis = description.strip()
            elif isinstance(description, dict):
                synopsis = (description.get("value") or "").strip()
            else:
                synopsis = None

            time.sleep(sleep_s)
            return synopsis

        except requests.exceptions.HTTPError:
            if r.status_code >= 500:
                print(f"Error {r.status_code} (servidor). Reintentando en {delay}s...")
            else:
                # 4xx → no reintentamos
                raise
        
        except requests.exceptions.RequestException:
            print(f"Error de conexión. Reintentando en {delay}s...")
        
        time.sleep(min(2 ** attempt, 60))
        attempt += 1


## AQUÍ ES DONDE TENGO QUE AÑADIR PARA LA SINOPSIS ##

######################################################################################################




def build_dataset(per_genre: int = 200) -> pd.DataFrame:
    rows = []
    for genre, subject in GENRE_TO_SUBJECT.items():
        works = fetch_subject_works(subject, limit=per_genre)
        for w in works[:per_genre]:
            rows.append({
                "title": w.get("title"),
                "author": best_author(w),
                "year": best_year(w),
                "genre": genre,
                "openlibrary_work_key": w.get("key")
            })

    df = pd.DataFrame(rows)
    return df

def basic_clean(df) -> pd.DataFrame:

    # Limpieza básica
    for c in ["title", "author", "genre"]:
        df[c] = df[c].astype("string").str.strip()

    df = df[df["title"].notna() & (df["title"].str.len() > 0)].copy()

    # Deduplicación simple (título + autor + año)
    df["dedupe"] = (
        df["title"].fillna("") + "||" +
        df["author"].fillna("") + "||" +
        df["year"].fillna(-1).astype("int64").astype("string")
    )
    df = df.drop_duplicates("dedupe").drop(columns=["dedupe"])

    return df


df = build_dataset(per_genre=200)  # ajustar a 50/200/1000 según se quiera. ¡Es por género!
df.to_csv("books_multi_genre.csv", index=False, encoding="utf-8")
# df = basic_clean(df)
print("Filas:", len(df))
print(df.head(10).to_string(index=False))

Filas: 1600
                           title                 author  year   genre openlibrary_work_key
Alice's Adventures in Wonderland          Lewis Carroll  1865 Fantasy     /works/OL138052W
      The Wonderful Wizard of Oz          L. Frank Baum  1899 Fantasy      /works/OL18417W
                 Treasure Island Robert Louis Stevenson  1880 Fantasy      /works/OL24034W
              Gulliver's Travels         Jonathan Swift  1726 Fantasy      /works/OL20600W
       A Midsummer Night's Dream    William Shakespeare  1600 Fantasy     /works/OL259010W
                      The Prince    Niccolò Machiavelli  1515 Fantasy    /works/OL1089297W
       Through the Looking-Glass          Lewis Carroll  1865 Fantasy     /works/OL151406W
         The Wind in the Willows        Kenneth Grahame  1908 Fantasy   /works/OL28570037W
            Five Children and It           Edith Nesbit  1905 Fantasy      /works/OL99499W
     The Princess and the Goblin       George MacDonald  1872 Fantasy      /works/OL15449W

In [49]:
rows = []
contador = 1
for r in df.itertuples():
    print(f"Recogiendo sinopsis del libro número {contador}: {r.title}")
    synopsis = f_synopsis(r.openlibrary_work_key)
    rows.append({
        "openlibrary_work_key": r.openlibrary_work_key,
        "synopsis": synopsis
    })
    contador+=1

df_synopsis = pd.DataFrame(rows)
df_synopsis

Recogiendo sinopsis del libro número 1: Alice's Adventures in Wonderland
Recogiendo sinopsis del libro número 2: The Wonderful Wizard of Oz
Recogiendo sinopsis del libro número 3: Treasure Island
Recogiendo sinopsis del libro número 4: Gulliver's Travels
Recogiendo sinopsis del libro número 5: A Midsummer Night's Dream
Recogiendo sinopsis del libro número 6: The Prince
Recogiendo sinopsis del libro número 7: Through the Looking-Glass
Recogiendo sinopsis del libro número 8: The Wind in the Willows
Recogiendo sinopsis del libro número 9: Five Children and It
Recogiendo sinopsis del libro número 10: The Princess and the Goblin
Recogiendo sinopsis del libro número 11: The Lost World
Recogiendo sinopsis del libro número 12: The Marvelous Land of Oz
Recogiendo sinopsis del libro número 13: Ozma of Oz
Recogiendo sinopsis del libro número 14: Le petit prince
Recogiendo sinopsis del libro número 15: The Emerald City of Oz
Recogiendo sinopsis del libro número 16: Dorothy and the Wizard in Oz
Recogiendo sinopsis del libro número 17: The Lost Princess of Oz
Recogiendo sinopsis del libro número 18: The Story of the Amulet
Recogiendo sinopsis del libro número 19: The Complete Life and Adventures of Santa Claus
Recogiendo sinopsis del libro número 20: Alice's Adventures in Wonderland / Through the Looking Glass
Recogiendo sinopsis del libro número 21: The Road to Oz
Recogiendo sinopsis del libro número 22: Nineteen Eighty-Four
Recogiendo sinopsis del libro número 23: The Sea Fairies
Recogiendo sinopsis del libro número 24: Baum's American Fairy Tales
Recogiendo sinopsis del libro número 25: Sky Island
Recogiendo sinopsis del libro número 26: The Scarecrow of Oz
Recogiendo sinopsis del libro número 27: The Patchwork Girl of Oz
Recogiendo sinopsis del libro número 28: The Magic of Oz
Recogiendo sinopsis del libro número 29: Tik-Tok of Oz
Recogiendo sinopsis del libro número 30: Rinkitink in Oz
Recogiendo sinopsis del libro número 31: The Enchanted Castle
Recogiendo sinopsis del libro número 32: Phantastes
Recogiendo sinopsis del libro número 33: The Tin Woodman of Oz
Recogiendo sinopsis del libro número 34: The Hobbit
Recogiendo sinopsis del libro número 35: Glinda of Oz
Recogiendo sinopsis del libro número 36: The Magic City
Recogiendo sinopsis del libro número 37: Peter Pan
Recogiendo sinopsis del libro número 38: The Phoenix and the Carpet
Recogiendo sinopsis del libro número 39: Le avventure di Pinocchio
Recogiendo sinopsis del libro número 40: Le Tour du Monde en Quatre-Vingts Jours
Recogiendo sinopsis del libro número 41: Harry Potter and the Philosopher's Stone
Recogiendo sinopsis del libro número 42: News from nowhere, or, An epoch of rest, being some chapters from a utopian romance
Recogiendo sinopsis del libro número 43: À rebours
Recogiendo sinopsis del libro número 44: The Secret Agent
Recogiendo sinopsis del libro número 45: Puck of Pook's Hill
Recogiendo sinopsis del libro número 46: Harry Potter and the Chamber of Secrets
Recogiendo sinopsis del libro número 47: The Fellowship of the Ring
Recogiendo sinopsis del libro número 48: The Enchanted Island of Yew
Recogiendo sinopsis del libro número 49: After London
Recogiendo sinopsis del libro número 50: Harry Potter and the Prisoner of Azkaban
Recogiendo sinopsis del libro número 51: The Two Towers
Recogiendo sinopsis del libro número 52: The Return of the King
Recogiendo sinopsis del libro número 53: The Royal Book of Oz
Recogiendo sinopsis del libro número 54: Jurgen
Recogiendo sinopsis del libro número 55: The wood beyond the world
Recogiendo sinopsis del libro número 56: Harry Potter and the Order of the Phoenix
Recogiendo sinopsis del libro número 57: Harry Potter and the Goblet of Fire
Recogiendo sinopsis del libro número 58: Мастер и Маргарита
Recogiendo sinopsis del libro número 59: Sylvie and Bruno
Recogiendo sinopsis del libro número 60: The Moon Pool
Recogiendo sinopsis del libro número 61: The reluctant dragon
Recogiendo sinopsis del libro número 62: The Story of Doctor Dolittle
Recogiendo sinopsis del libro número 63: Charlie and the Chocolate Factory
Recogiendo sinopsis del libro número 64: The Well at the World's End
Recogiendo sinopsis del libro número 65: The water-babies: a fairy tale for a land-baby
Recogiendo sinopsis del libro número 66: A Princess of Mars
Recogiendo sinopsis del libro número 67: Cien años de soledad
Recogiendo sinopsis del libro número 68: Brood of the Witch-Queen
Recogiendo sinopsis del libro número 69: The Horse and His Boy
Recogiendo sinopsis del libro número 70: Fifty-one tales
Recogiendo sinopsis del libro número 71: Harry Potter and the Half-Blood Prince
Recogiendo sinopsis del libro número 72: The little white bird, or, Adventures in Kensington gardens
Recogiendo sinopsis del libro número 73: Wet Magic
Recogiendo sinopsis del libro número 74: Peter Pan in Kensington Gardens
Recogiendo sinopsis del libro número 75: The Magician's Nephew
Recogiendo sinopsis del libro número 76: The Master Key
Recogiendo sinopsis del libro número 77: The Lion, the Witch and the Wardrobe
Recogiendo sinopsis del libro número 78: The Voyages of Doctor Dolittle
Recogiendo sinopsis del libro número 79: The house of the Wolfings
Recogiendo sinopsis del libro número 80: The Crock of Gold
Recogiendo sinopsis del libro número 81: The Silmarillion
Recogiendo sinopsis del libro número 82: Charlotte's Web
Recogiendo sinopsis del libro número 83: James and the Giant Peach
Recogiendo sinopsis del libro número 84: Prince Caspian
Recogiendo sinopsis del libro número 85: Northern Lights
Recogiendo sinopsis del libro número 86: Harry Potter and the Deathly Hallows
Recogiendo sinopsis del libro número 87: The Silver Chair
Recogiendo sinopsis del libro número 88: The BFG
Recogiendo sinopsis del libro número 89: A Game of Thrones
Recogiendo sinopsis del libro número 90: Lost Horizon
Recogiendo sinopsis del libro número 91: Where the Wild Things Are
Recogiendo sinopsis del libro número 92: Little Wizard stories of Oz
Recogiendo sinopsis del libro número 93: Morning Star
Recogiendo sinopsis del libro número 94: Catching Fire
Recogiendo sinopsis del libro número 95: A strange manuscript found in a copper cylinder
Recogiendo sinopsis del libro número 96: Momo oder Die seltsame Geschichte von den Zeit-Dieben und von dem Kind, das den Menschen die gestohlene Zeit zurückbrachte
Recogiendo sinopsis del libro número 97: The Last Battle
Recogiendo sinopsis del libro número 98: The house behind the cedars
Recogiendo sinopsis del libro número 99: The Subtle Knife
Recogiendo sinopsis del libro número 100: Bridge to Terabithia
Recogiendo sinopsis del libro número 101: The Lightning Thief
Recogiendo sinopsis del libro número 102: The Voyage of the Dawn Treader
Recogiendo sinopsis del libro número 103: Watership Down
Recogiendo sinopsis del libro número 104: Coraline
Recogiendo sinopsis del libro número 105: The Gunslinger
Recogiendo sinopsis del libro número 106: Artemis Fowl
Recogiendo sinopsis del libro número 107: Figures of Earth
Recogiendo sinopsis del libro número 108: The Colour of Magic
Recogiendo sinopsis del libro número 109: New Moon
Recogiendo sinopsis del libro número 110: The wonderful visit
Recogiendo sinopsis del libro número 111: Eragon
Recogiendo sinopsis del libro número 112: The Cat in the Hat
Recogiendo sinopsis del libro número 113: Vikram and the Vampire
Recogiendo sinopsis del libro número 114: Hänsel und Gretel
Recogiendo sinopsis del libro número 115: A Wizard of Earthsea
Recogiendo sinopsis del libro número 116: The Amber Spyglass
Recogiendo sinopsis del libro número 117: The Mysterious Stranger
Recogiendo sinopsis del libro número 118: The Magical Monarch of Mo
Recogiendo sinopsis del libro número 119: The Once and Future King
Recogiendo sinopsis del libro número 120: Prince Prigio
Recogiendo sinopsis del libro número 121: Thumbelina
Recogiendo sinopsis del libro número 122: Dragonflight
Recogiendo sinopsis del libro número 123: A Clash of Kings
Recogiendo sinopsis del libro número 124: A Prisoner in Fairyland
Recogiendo sinopsis del libro número 125: The Name of the Wind
Recogiendo sinopsis del libro número 126: The demi-gods
Recogiendo sinopsis del libro número 127: The Nursery Alice
Recogiendo sinopsis del libro número 128: Indian Fairy Tales
Recogiendo sinopsis del libro número 129: Good Omens
Recogiendo sinopsis del libro número 130: The Blazing World
Recogiendo sinopsis del libro número 131: American Gods
Recogiendo sinopsis del libro número 132: Eldest
Recogiendo sinopsis del libro número 133: The Sea of Monsters
Recogiendo sinopsis del libro número 134: Chitty-Chitty-Bang-Bang, the magical car
Recogiendo sinopsis del libro número 135: Wizard and Glass
Recogiendo sinopsis del libro número 136: Doctor Doolittle's circus
Recogiendo sinopsis del libro número 137: A Torre Negra
Recogiendo sinopsis del libro número 138: Tintenherz
Recogiendo sinopsis del libro número 139: A Feast for Crows
Recogiendo sinopsis del libro número 140: The Eye of the World
Recogiendo sinopsis del libro número 141: Nils Holgerssons underbara resa genom Sverige
Recogiendo sinopsis del libro número 142: Don Rodriguez
Recogiendo sinopsis del libro número 143: The Tombs of Atuan
Recogiendo sinopsis del libro número 144: Doctor Dolittle in the moon
Recogiendo sinopsis del libro número 145: Le chat botté
Recogiendo sinopsis del libro número 146: Tarzan the Invincible (Ace Classic SF, F-189)
Recogiendo sinopsis del libro número 147: Doctor Dolittle's post office
Recogiendo sinopsis del libro número 148: The Eyes of the Dragon
Recogiendo sinopsis del libro número 149: The Centaur
Recogiendo sinopsis del libro número 150: Life, the Universe and Everything
Recogiendo sinopsis del libro número 151: The talisman
Recogiendo sinopsis del libro número 152: Night Shift
Recogiendo sinopsis del libro número 153: The Phantom Tollbooth
Recogiendo sinopsis del libro número 154: Artemis Fowl and the Eternity Code
Recogiendo sinopsis del libro número 155: The Battle of the Labyrinth
Recogiendo sinopsis del libro número 156: The Farthest Shore
Recogiendo sinopsis del libro número 157: The Titan's Curse
Recogiendo sinopsis del libro número 158: Stardust
Recogiendo sinopsis del libro número 159: Adela Cathcart
Recogiendo sinopsis del libro número 160: Mort
Recogiendo sinopsis del libro número 161: Everything's Eventual. 14 Dark Tales
Recogiendo sinopsis del libro número 162: Something Wicked This Way Comes
Recogiendo sinopsis del libro número 163: The Black Cauldron
Recogiendo sinopsis del libro número 164: The Chronicles of Narnia
Recogiendo sinopsis del libro número 165: The Light Fantastic
Recogiendo sinopsis del libro número 166: A thin ghost and others
Recogiendo sinopsis del libro número 167: Redwall
Recogiendo sinopsis del libro número 168: Yu-Gi-Oh!
Recogiendo sinopsis del libro número 169: Dinosaurs Before Dark
Recogiendo sinopsis del libro número 170: The dark is rising
Recogiendo sinopsis del libro número 171: Black house
Recogiendo sinopsis del libro número 172: The Enchanted Typewriter
Recogiendo sinopsis del libro número 173: The Last Olympian
Recogiendo sinopsis del libro número 174: Mary Poppins
Recogiendo sinopsis del libro número 175: Die unendliche Geschichte
Recogiendo sinopsis del libro número 176: Guards! Guards!
Recogiendo sinopsis del libro número 177: Rose Madder
Recogiendo sinopsis del libro número 178: Tom's Midnight Garden
Recogiendo sinopsis del libro número 179: A Storm of Swords
Recogiendo sinopsis del libro número 180: Dragonquest
Recogiendo sinopsis del libro número 181: Doctor Dolittle's garden
Recogiendo sinopsis del libro número 182: The Regulators
Recogiendo sinopsis del libro número 183: Farmer Giles of Ham
Recogiendo sinopsis del libro número 184: Trollkarlens hatt
Recogiendo sinopsis del libro número 185: Wicked
Recogiendo sinopsis del libro número 186: La Petite Sirene (French Well Loved Tales)
Recogiendo sinopsis del libro número 187: Mostly Harmless
Recogiendo sinopsis del libro número 188: The Lost Hero
Recogiendo sinopsis del libro número 189: The Book Of Three
Recogiendo sinopsis del libro número 190: Equal Rites
Recogiendo sinopsis del libro número 191: Brisingr
Recogiendo sinopsis del libro número 192: Tale of Despereaux
Recogiendo sinopsis del libro número 193: Wizard's First Rule
Recogiendo sinopsis del libro número 194: Wintersmith
Recogiendo sinopsis del libro número 195: Small Gods
Recogiendo sinopsis del libro número 196: Corduroy
Recogiendo sinopsis del libro número 197: Flat Stanley
Recogiendo sinopsis del libro número 198: Jonathan Strange and Mr. Norrell
Recogiendo sinopsis del libro número 199: Over Sea, Under Stone (The Dark Is Rising #1)
Recogiendo sinopsis del libro número 200: Artemis Fowl and the Arctic Incident
Recogiendo sinopsis del libro número 201: Alice's Adventures in Wonderland
Recogiendo sinopsis del libro número 202: Frankenstein or The Modern Prometheus
Recogiendo sinopsis del libro número 203: The Wonderful Wizard of Oz
Recogiendo sinopsis del libro número 204: The Time Machine
Recogiendo sinopsis del libro número 205: The Lost World
Recogiendo sinopsis del libro número 206: Dracula
Recogiendo sinopsis del libro número 207: Brave New World
Recogiendo sinopsis del libro número 208: The Jewel of Seven Stars
Recogiendo sinopsis del libro número 209: The Iron Heel
Recogiendo sinopsis del libro número 210: Flatland
Recogiendo sinopsis del libro número 211: The Invisible Man
Recogiendo sinopsis del libro número 212: Nineteen Eighty-Four
Recogiendo sinopsis del libro número 213: The Princess and Curdie
Recogiendo sinopsis del libro número 214: The War of the Worlds
Recogiendo sinopsis del libro número 215: The Napoleon of Notting Hill
Recogiendo sinopsis del libro número 216: The Last Man
Recogiendo sinopsis del libro número 217: Le Tour du Monde en Quatre-Vingts Jours
Recogiendo sinopsis del libro número 218: Vingt mille lieues sous les mers
Recogiendo sinopsis del libro número 219: The Strange Case of Dr. Jekyll and Mr. Hyde
Recogiendo sinopsis del libro número 220: News from nowhere, or, An epoch of rest, being some chapters from a utopian romance
Recogiendo sinopsis del libro número 221: The Poison Belt
Recogiendo sinopsis del libro número 222: The Secret Agent
Recogiendo sinopsis del libro número 223: The Machine Stops
Recogiendo sinopsis del libro número 224: The Island of Dr. Moreau
Recogiendo sinopsis del libro número 225: After London
Recogiendo sinopsis del libro número 226: The Coming Race
Recogiendo sinopsis del libro número 227: Fahrenheit 451
Recogiendo sinopsis del libro número 228: The wood beyond the world
Recogiendo sinopsis del libro número 229: The Moon Pool
Recogiendo sinopsis del libro número 230: At the Earth's Core
Recogiendo sinopsis del libro número 231: In the days of the comet
Recogiendo sinopsis del libro número 232: The warlord of Mars #3
Recogiendo sinopsis del libro número 233: Мы
Recogiendo sinopsis del libro número 234: De la terre à la lune
Recogiendo sinopsis del libro número 235: Thuvia, Maid of Mars
Recogiendo sinopsis del libro número 236: A Princess of Mars
Recogiendo sinopsis del libro número 237: Voyage au Centre de la Terre
Recogiendo sinopsis del libro número 238: When the Sleeper Awakes
Recogiendo sinopsis del libro número 239: The Chessmen of Mars
Recogiendo sinopsis del libro número 240: The food of the gods and how it came to earth
Recogiendo sinopsis del libro número 241: The Beasts of Tarzan (Classic Ace SF, F-203)
Recogiendo sinopsis del libro número 242: The Handmaid's Tale
Recogiendo sinopsis del libro número 243: It Can't Happen Here
Recogiendo sinopsis del libro número 244: R.U.R. and The insect play
Recogiendo sinopsis del libro número 245: The Hunger Games
Recogiendo sinopsis del libro número 246: The Martian Chronicles
Recogiendo sinopsis del libro número 247: When the World Shook
Recogiendo sinopsis del libro número 248: A Clockwork Orange
Recogiendo sinopsis del libro número 249: A Game of Thrones
Recogiendo sinopsis del libro número 250: Slaughterhouse-Five
Recogiendo sinopsis del libro número 251: Armageddon 2419 AD
Recogiendo sinopsis del libro número 252: The Hitch Hiker's Guide to the Galaxy
Recogiendo sinopsis del libro número 253: Dune
Recogiendo sinopsis del libro número 254: On the Beach
Recogiendo sinopsis del libro número 255: 2001
Recogiendo sinopsis del libro número 256: Gullivar of Mars
Recogiendo sinopsis del libro número 257: Catching Fire
Recogiendo sinopsis del libro número 258: The First Men in the Moon
Recogiendo sinopsis del libro número 259: Charlie and the Great Glass Elevator
Recogiendo sinopsis del libro número 260: Cinq semaines en ballon
Recogiendo sinopsis del libro número 261: A strange manuscript found in a copper cylinder
Recogiendo sinopsis del libro número 262: Little Fuzzy
Recogiendo sinopsis del libro número 263: The Giver
Recogiendo sinopsis del libro número 264: The house behind the cedars
Recogiendo sinopsis del libro número 265: The ship of Ishtar
Recogiendo sinopsis del libro número 266: Ender's Game
Recogiendo sinopsis del libro número 267: A Wrinkle in Time
Recogiendo sinopsis del libro número 268: Lord of the World
Recogiendo sinopsis del libro número 269: A Modern Utopia
Recogiendo sinopsis del libro número 270: Les Robots
Recogiendo sinopsis del libro número 271: Foundation
Recogiendo sinopsis del libro número 272: Mockingjay
Recogiendo sinopsis del libro número 273: The water of the Wondrous isles
Recogiendo sinopsis del libro número 274: The Gunslinger
Recogiendo sinopsis del libro número 275: Jurassic Park
Recogiendo sinopsis del libro número 276: Deception Point
Recogiendo sinopsis del libro número 277: The Restaurant at the End of the Universe
Recogiendo sinopsis del libro número 278: The Time Traders
Recogiendo sinopsis del libro número 279: Plague Ship
Recogiendo sinopsis del libro número 280: Do Androids Dream of Electric Sheep?
Recogiendo sinopsis del libro número 281: Star Born
Recogiendo sinopsis del libro número 282: The Left Hand of Darkness
Recogiendo sinopsis del libro número 283: The Blind Assassin
Recogiendo sinopsis del libro número 284: The Dead Zone
Recogiendo sinopsis del libro número 285: Divergent
Recogiendo sinopsis del libro número 286: La casa verde
Recogiendo sinopsis del libro número 287: Junkyard Planet
Recogiendo sinopsis del libro número 288: Eragon
Recogiendo sinopsis del libro número 289: The Adventures of Captain Underpants
Recogiendo sinopsis del libro número 290: The Stand
Recogiendo sinopsis del libro número 291: The Man in the High Castle
Recogiendo sinopsis del libro número 292: L'Île mystérieuse
Recogiendo sinopsis del libro número 293: A Wizard of Earthsea
Recogiendo sinopsis del libro número 294: The Amber Spyglass
Recogiendo sinopsis del libro número 295: The Illustrated Man
Recogiendo sinopsis del libro número 296: Second Foundation
Recogiendo sinopsis del libro número 297: Foundation and Empire
Recogiendo sinopsis del libro número 298: Stranger in a Strange Land
Recogiendo sinopsis del libro número 299: The man who ended war
Recogiendo sinopsis del libro número 300: Storm Over Warlock
Recogiendo sinopsis del libro número 301: Flowers for Algernon
Recogiendo sinopsis del libro número 302: The Lost World
Recogiendo sinopsis del libro número 303: Dragonflight
Recogiendo sinopsis del libro número 304: Tales of space and time
Recogiendo sinopsis del libro número 305: Atlas Shrugged (Centennial Ed. HC)
Recogiendo sinopsis del libro número 306: Star Maker
Recogiendo sinopsis del libro número 307: Firestarter
Recogiendo sinopsis del libro número 308: A Clash of Kings
Recogiendo sinopsis del libro número 309: Solaris
Recogiendo sinopsis del libro número 310: The Dispossessed
Recogiendo sinopsis del libro número 311: Válka s mloky
Recogiendo sinopsis del libro número 312: So long, and thanks for all the fish
Recogiendo sinopsis del libro número 313: The Blazing World
Recogiendo sinopsis del libro número 314: Childhood’s End
Recogiendo sinopsis del libro número 315: A Canticle for Leibowitz

     openlibrary_work_key                                           synopsis
0        /works/OL138052W  Alice's Adventures in Wonderland (commonly Ali...
1         /works/OL18417W  Over a century after its initial publication, ...
2         /works/OL24034W  Traditionally considered a coming-of-age story...
3         /works/OL20600W  A parody of traveler’s tales and a satire of h...
4        /works/OL259010W  One night two young couples run into an enchan...
...                   ...                                                ...
1595    /works/OL2147971W  When Fanny Trollope set sail for America in 18...
1596    /works/OL1496762W                                               None
1597      /works/OL65487W  Runaway best-selling PC hardware book of all t...
1598      /works/OL53604W  Helen Keller graduated cum laude from Radcliff...
1599    /works/OL5727686W  Eckhart Tolle has emerged as one of today's mo...

[1600 rows x 2 columns]

In [96]:
# Eliminamos duplicados
df_synopsis_clean = df_synopsis.drop_duplicates("openlibrary_work_key")
print("Filas:", len(df_synopsis_clean))
print(df_synopsis_clean.head(10).to_string(index=False))

Filas: 1461
openlibrary_work_key                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              synopsis
    /works/OL138052W                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Alice's Adventures in Wonderland (commonly Alice in Wonderland) is an 1865 English children's novel by Lewis Carroll. A young girl named Alice falls through a rabbit hole into a fantasy world of anthropomorphic creatures. It is seen as an example of the literary nonsense genre.\r\n\r\nOne of the best-known works of Victorian literature, its narrative, structure, characters and imagery have had huge influence on popular culture and literature, especially in the fantasy genre.
     /works/OL18417W                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Over a century after its initial publication, The Wonderful Wizard of Oz is still captivating the hearts of countless readers. Come adventure with Dorothy and her three friends: the Scarecrow, the Tin Woodman, and the Cowardly Lion, as they follow the Yellow Brick Road to the Emerald City for an audience with the Great Oz, the mightiest Wizard in the land, and the only one that can return Dorothy to her home in Kansas.
     /works/OL24034W                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Traditionally considered a coming-of-age story, Treasure Island is an adventure tale known for its atmosphere, characters and action, and also as a wry commentary on the ambiguity of morality — as seen in Long John Silver — unusual for children's literature then and now. It is one of the most frequently dramatized of all novels. The influence of Treasure Island on popular perceptions of pirates is enormous, including treasure maps marked with an "X", schooners, the Black Spot, tropical islands, and one-legged seamen carrying parrots on their shoulders
     /works/OL20600W A parody of traveler’s tales and a satire of human nature, “Gulliver’s Travels” is Jonathan Swift’s most famous work which was first published in 1726. An immensely popular tale ever since its original publication, “Gulliver’s Travels” is the story of its titular character, Lemuel Gulliver, a man who loves to travel. A series of four journeys are detailed in which Gulliver finds himself in a number of amusing and precarious situations. In the first voyage, Gulliver is imprisoned by a race of tiny people, the Lilliputians, when following a shipwreck he is washed upon the shores of their island country. In his second voyage Gulliver finds himself abandoned in Brobdingnag, a land of giants, where he is exhibited for their amusement. In his third voyage, Gulliver once again finds himself marooned; fortunately he is rescued by the flying island of Laputa, a kingdom devoted to the arts of music and mathematics. He subsequently travels to the surrounding lands of Balnibarbi, Luggnagg, Glubbdubdrib, and Japan. Finally in his last voyage, when he is set adrift by a mutinous crew, he finds himself in the curious Country of the Houyhnhnms. Through the various experiences of Gulliver, Swift brilliantly satirizes the political and cultural environment of his time in addition to creating a lasting and enchanting tale of fantasy. This edition is illustrated by Milo Winter and includes an introduction by George R. Dennis.
    /works/OL259010W                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                One night two young couples run into an enchanted forest in an attempt to escape their problems. But these four humans do not realize that the forest is filled with fairies and hobgoblins who love making mischief. When Oberon, the Fairy King, and his loyal hobgoblin servant, Puck, intervene in human affairs, the fate of these young couples is magically and hilariously transformed. Like a classic fairy tale, this retelling of William Shakespeare's most beloved comedy is perfect for older readers who will find much to treasure and for younger readers who will love hearing the story read aloud.
   /works/OL1089297W                                                                                                                                                                                                  The Prince (Italian: Il Principe [il ˈprintʃipe]; Latin: De Principatibus) is a 16th-century political treatise written by Italian diplomat and political theorist Niccolò Machiavelli as an instruction guide for new princes and royals. The general theme of The Prince is of accepting that the aims of princes – such as glory and survival – can justify the use of immoral means to achieve those ends.\r\n\r\nFrom Machiavelli's correspondence, a version appears to have been distributed in 1513, using a Latin title, De Principatibus (Of Principalities). However, the printed version was not published until 1532, five years after Machiavelli's death. This was carried out with the permission of the Medici pope Clement VII, but "long before then, in fact since the first appearance of The Prince in manuscript, controversy had swirled about his writings".\r\n\r\nAlthough The Prince was written as if it were a traditional work in the mirrors for princes style, it was generally agreed as being especially innovative. This is partly because it was written in the vernacular Italian rather than Latin, a practice that had become increasingly popular since the publication of Dante's Divine Comedy and other works of Renaissance literature.
    /works/OL151406W                                                                                                                                                                                                                                                                                                                                                                                                                                                                *Through the Looking-Glass, and What Alice Found There* (1871) is a work of children's literature by Lewis Carroll (Charles Lutwidge Dodgson), generally categorized in the fairy tale genre. It is the sequel to *Alice's Adventures in Wonderland* (1865). Although it makes no reference to the events in the earlier book, the themes and settings of *Through the Looking-Glass* make it a kind of mirror image of Wonderland: the first book begins outdoors, in the warm month of May, uses frequent changes in size as a plot device, and draws on the imagery of playing cards; the second opens indoors on a snowy, wintry night exactly six months later, on November 4 (the day before Guy Fawkes Night), uses frequent changes in time and spatial directions as a plot device, and draws on the imagery of chess. In it, there are many mirror themes, including opposites, time running backwards, and so on. ([Wikipedia][1])\r\n\r\n\r\n  [1]: http://en.wikipedia.org/wiki/Through_the_Looking-Glass
  /works/OL28570037W                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         The adventures of four amiable animals, Rat, Toad, Mole and Badger, along a river in the English countryside.
     /works/OL99499W                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Haven't you ever thought what you would wish for if you were granted three wishes? In Nesbit's delightful classic, five siblings find a creature that grants their wishes, but as the old saying goes: be careful what you wish for, it might come true...
     /works/OL15449W                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      There was once a little princess whose father was king over a great country full of mountains and valleys. His palace was built upon one of the mountains, and was very grand and beautiful. The princess, whose name was Irene, was born there, but she was sent soon after her birth, because her mother was not very strong, to be brought up by country people in a large house, half castle, half farmhouse, on the side of another mountain, about half-way between its base and its peak.

In [102]:
# Por último unimos los dataframes para trabajar con un único dataframe en el que se incluya la sinopsis y generamos el CSV
df_final = df.merge(df_synopsis_clean, how="left", on="openlibrary_work_key")
# df_final.to_csv("books_with_synopsis.csv", index=False, encoding="utf-8")
print("Filas:", len(df_final))
print(df_final.head(10).to_string(index=False))

Filas: 1600
                           title                 author  year   genre openlibrary_work_key                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              synopsis
Alice's Adventures in Wonderland          Lewis Carroll  1865 Fantasy     /works/OL138052W                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Alice's Adventures in Wonderland (commonly Alice in Wonderland) is an 1865 English children's novel by Lewis Carroll. A young girl named Alice falls through a rabbit hole into a fantasy world of anthropomorphic creatures. It is seen as an example of the literary nonsense genre.\r\n\r\nOne of the best-known works of Victorian literature, its narrative, structure, characters and imagery have had huge influence on popular culture and literature, especially in the fantasy genre.
      The Wonderful Wizard of Oz          L. Frank Baum  1899 Fantasy      /works/OL18417W                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Over a century after its initial publication, The Wonderful Wizard of Oz is still captivating the hearts of countless readers. Come adventure with Dorothy and her three friends: the Scarecrow, the Tin Woodman, and the Cowardly Lion, as they follow the Yellow Brick Road to the Emerald City for an audience with the Great Oz, the mightiest Wizard in the land, and the only one that can return Dorothy to her home in Kansas.
                 Treasure Island Robert Louis Stevenson  1880 Fantasy      /works/OL24034W                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Traditionally considered a coming-of-age story, Treasure Island is an adventure tale known for its atmosphere, characters and action, and also as a wry commentary on the ambiguity of morality — as seen in Long John Silver — unusual for children's literature then and now. It is one of the most frequently dramatized of all novels. The influence of Treasure Island on popular perceptions of pirates is enormous, including treasure maps marked with an "X", schooners, the Black Spot, tropical islands, and one-legged seamen carrying parrots on their shoulders
              Gulliver's Travels         Jonathan Swift  1726 Fantasy      /works/OL20600W A parody of traveler’s tales and a satire of human nature, “Gulliver’s Travels” is Jonathan Swift’s most famous work which was first published in 1726. An immensely popular tale ever since its original publication, “Gulliver’s Travels” is the story of its titular character, Lemuel Gulliver, a man who loves to travel. A series of four journeys are detailed in which Gulliver finds himself in a number of amusing and precarious situations. In the first voyage, Gulliver is imprisoned by a race of tiny people, the Lilliputians, when following a shipwreck he is washed upon the shores of their island country. In his second voyage Gulliver finds himself abandoned in Brobdingnag, a land of giants, where he is exhibited for their amusement. In his third voyage, Gulliver once again finds himself marooned; fortunately he is rescued by the flying island of Laputa, a kingdom devoted to the arts of music and mathematics. He subsequently travels to the surrounding lands of Balnibarbi, Luggnagg, Glubbdubdrib, and Japan. Finally in his last voyage, when he is set adrift by a mutinous crew, he finds himself in the curious Country of the Houyhnhnms. Through the various experiences of Gulliver, Swift brilliantly satirizes the political and cultural environment of his time in addition to creating a lasting and enchanting tale of fantasy. This edition is illustrated by Milo Winter and includes an introduction by George R. Dennis.
       A Midsummer Night's Dream    William Shakespeare  1600 Fantasy     /works/OL259010W                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                One night two young couples run into an enchanted forest in an attempt to escape their problems. But these four humans do not realize that the forest is filled with fairies and hobgoblins who love making mischief. When Oberon, the Fairy King, and his loyal hobgoblin servant, Puck, intervene in human affairs, the fate of these young couples is magically and hilariously transformed. Like a classic fairy tale, this retelling of William Shakespeare's most beloved comedy is perfect for older readers who will find much to treasure and for younger readers who will love hearing the story read aloud.
                      The Prince    Niccolò Machiavelli  1515 Fantasy    /works/OL1089297W                                                                                                                                                                                                  The Prince (Italian: Il Principe [il ˈprintʃipe]; Latin: De Principatibus) is a 16th-century political treatise written by Italian diplomat and political theorist Niccolò Machiavelli as an instruction guide for new princes and royals. The general theme of The Prince is of accepting that the aims of princes – such as glory and survival – can justify the use of immoral means to achieve those ends.\r\n\r\nFrom Machiavelli's correspondence, a version appears to have been distributed in 1513, using a Latin title, De Principatibus (Of Principalities). However, the printed version was not published until 1532, five years after Machiavelli's death. This was carried out with the permission of the Medici pope Clement VII, but "long before then, in fact since the first appearance of The Prince in manuscript, controversy had swirled about his writings".\r\n\r\nAlthough The Prince was written as if it were a traditional work in the mirrors for princes style, it was generally agreed as being especially innovative. This is partly because it was written in the vernacular Italian rather than Latin, a practice that had become increasingly popular since the publication of Dante's Divine Comedy and other works of Renaissance literature.
       Through the Looking-Glass          Lewis Carroll  1865 Fantasy     /works/OL151406W                                                                                                                                                                                                                                                                                                                                                                                                                                                                *Through the Looking-Glass, and What Alice Found There* (1871) is a work of children's literature by Lewis Carroll (Charles Lutwidge Dodgson), generally categorized in the fairy tale genre. It is the sequel to *Alice's Adventures in Wonderland* (1865). Although it makes no reference to the events in the earlier book, the themes and settings of *Through the Looking-Glass* make it a kind of mirror image of Wonderland: the first book begins outdoors, in the warm month of May, uses frequent changes in size as a plot device, and draws on the imagery of playing cards; the second opens indoors on a snowy, wintry night exactly six months later, on November 4 (the day before Guy Fawkes Night), uses frequent changes in time and spatial directions as a plot device, and draws on the imagery of chess. In it, there are many mirror themes, including opposites, time running backwards, and so on. ([Wikipedia][1])\r\n\r\n\r\n  [1]: http://en.wikipedia.org/wiki/Through_the_Looking-Glass
         The Wind in the Willows        Kenneth Grahame  1908 Fantasy   /works/OL28570037W                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         The adventures of four amiable animals, Rat, Toad, Mole and Badger, along a river in the English countryside.
            Five Children and It           Edith Nesbit  1905 Fantasy      /works/OL99499W                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Haven't you ever thought what you would wish for if you were granted three wishes? In Nesbit's delightful classic, five siblings find a creature that grants their wishes, but as the old saying goes: be careful what you wish for, it might come true...
     The Princess and the Goblin       George MacDonald  1872 Fantasy      /works/OL15449W                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      There was once a little princess whose father was king over a great country full of mountains and valleys. His palace was built upon one of the mountains, and was very grand and beautiful. The princess, whose name was Irene, was born there, but she was sent soon after her birth, because her mother was not very strong, to be brought up by country people in a large house, half castle, half farmhouse, on the side of another mountain, about half-way between its base and its peak.

In [84]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1600 entries, 0 to 1599
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   title                 1600 non-null   object
 1   author                1600 non-null   object
 2   year                  1600 non-null   int64
 3   genre                 1600 non-null   object
 4   openlibrary_work_key  1600 non-null   object
 5   synopsis              1512 non-null   object
dtypes: int64(1), object(5)
memory usage: 75.1+ KB

In [85]:
df_final['genre'].value_counts(dropna=False)

genre
Fantasy               200
Science fiction       200
Mystery               200
Romance               200
Horror                200
Historical fiction    200
Young adult           200
Non fiction           200
Name: count, dtype: int64

In [86]:
df_clean = basic_clean(df_final)
print("Filas:", len(df_clean))
df_clean.head(10)

Filas: 1461

,title,author,year,genre,openlibrary_work_key,synopsis
0,Alice's Adventures in Wonderland,Lewis Carroll,1865,Fantasy,/works/OL138052W,Alice's Adventures in Wonderland (commonly Ali...
1,The Wonderful Wizard of Oz,L. Frank Baum,1899,Fantasy,/works/OL18417W,"Over a century after its initial publication, ..."
2,Treasure Island,Robert Louis Stevenson,1880,Fantasy,/works/OL24034W,Traditionally considered a coming-of-age story...
3,Gulliver's Travels,Jonathan Swift,1726,Fantasy,/works/OL20600W,A parody of traveler’s tales and a satire of h...
4,A Midsummer Night's Dream,William Shakespeare,1600,Fantasy,/works/OL259010W,One night two young couples run into an enchan...
5,The Prince,Niccolò Machiavelli,1515,Fantasy,/works/OL1089297W,The Prince (Italian: Il Principe [il ˈprintʃip...
6,Through the Looking-Glass,Lewis Carroll,1865,Fantasy,/works/OL151406W,"*Through the Looking-Glass, and What Alice Fou..."
7,The Wind in the Willows,Kenneth Grahame,1908,Fantasy,/works/OL28570037W,"The adventures of four amiable animals, Rat, T..."
8,Five Children and It,Edith Nesbit,1905,Fantasy,/works/OL99499W,Haven't you ever thought what you would wish f...
9,The Princess and the Goblin,George MacDonald,1872,Fantasy,/works/OL15449W,There was once a little princess whose father ...

In [87]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1461 entries, 0 to 1599
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   title                 1461 non-null   string
 1   author                1461 non-null   string
 2   year                  1461 non-null   int64
 3   genre                 1461 non-null   string
 4   openlibrary_work_key  1461 non-null   object
 5   synopsis              1373 non-null   object
dtypes: int64(1), object(2), string(3)
memory usage: 79.9+ KB

In [88]:
df_clean['genre'].value_counts(dropna=False)

genre
Fantasy               200
Mystery               195
Non fiction           194
Romance               188
Young adult           180
Horror                177
Historical fiction    164
Science fiction       163
Name: count, dtype: Int64

In [104]:
df_final['year'].min()

0

In [89]:
df_clean['year'].min()

0

In [ ]:
# DF original
print(f"El intervalo de años de publicación va de {df_final['year'].min()} a {df_final['year'].max()}")

El intervalo de años de publicación va de 0 a 2025

In [ ]:
# DF sin duplicados
print(f"El intervalo de años de publicación va de {df_clean['year'].min()} a {df_clean['year'].max()}")

El intervalo de años de publicación va de 0 a 2025

In [106]:
# DF original
found = False

for row in df_final.itertuples(): 
    if row.year == 0:
        print(f'El título: {row.title} tiene un cero ({row.year}) como año de publicación.')
        found = True

if not found: 
    print('Todos los libros tienen año de publicación')

El título: The Invisible Man tiene un cero (0) como año de publicación.
El título: The War of the Worlds tiene un cero (0) como año de publicación.

In [92]:
# DF sin duplicados
found_clean = False

for row in df_clean.itertuples(): 
    if row.year == 0:
        print(f'El título: {row.title} tiene un cero ({row.year}) como año de publicación.')
        found_clean = True

if not found_clean: 
    print('Todos los libros tienen año de publicación')

El título: The Invisible Man tiene un cero (0) como año de publicación.
El título: The War of the Worlds tiene un cero (0) como año de publicación.

Cambiamos por los años que corresponde: 

- The Invisible Man -> 1897
- The War of the Worlds -> 1898

In [ ]:
#DF original
df_final.loc[df_final['title'] == 'The Invisible Man', 'year'] = 1897
df_final.loc[df_final['title'] == 'The War of the Worlds', 'year'] = 1898

# Comprobación del DF original
found = False

for row in df_final.itertuples(): 
    if row.year == 0:
        print(f'El título: {row.title} tiene un cero ({row.year}) como año de publicación.')
        found = True

if not found: 
    print('Todos los libros tienen año de publicación')

Todos los libros tienen año de publicación

In [ ]:
# DF sin duplicados
df_clean.loc[df_clean['title'] == 'The Invisible Man', 'year'] = 1897
df_clean.loc[df_clean['title'] == 'The War of the Worlds', 'year'] = 1898

# Comprobación de DF sin duplicados
found_clean = False

for row in df_clean.itertuples(): 
    if row.year == 0:
        print(f'El título: {row.title} tiene un cero ({row.year}) como año de publicación.')
        found_clean = True

if not found_clean: 
    print('Todos los libros tienen año de publicación')

Todos los libros tienen año de publicación

In [114]:
# Definir los límites
bins = [
    1400, 1500, 1600, 1700, 1800,
    1850, 1900, 1950, 1970, 1990,
    2000, 2010, 2020, 2027
]

labels = [
    "1400-1499",
    "1500-1599",
    "1600-1699",
    "1700-1799",
    "1800-1849",
    "1850-1899",
    "1900-1949",
    "1950-1969",
    "1970-1989",
    "1990-1999",
    "2000-2009",
    "2010-2019",
    "2020-2026"
]


# DF original 
df_final["periodo"] = pd.cut(
    df_final["year"],
    bins=bins,
    labels=labels,
    right=False
)


# DF sin duplicados
df_clean["periodo"] = pd.cut(
    df_clean["year"],
    bins=bins,
    labels=labels,
    right=False
)

In [115]:
df_final.head(3)

,title,author,year,genre,openlibrary_work_key,synopsis,periodo
0,Alice's Adventures in Wonderland,Lewis Carroll,1865,Fantasy,/works/OL138052W,Alice's Adventures in Wonderland (commonly Ali...,1850-1899
1,The Wonderful Wizard of Oz,L. Frank Baum,1899,Fantasy,/works/OL18417W,"Over a century after its initial publication, ...",1850-1899
2,Treasure Island,Robert Louis Stevenson,1880,Fantasy,/works/OL24034W,Traditionally considered a coming-of-age story...,1850-1899

In [117]:
df_clean.tail(3)

,title,author,year,genre,openlibrary_work_key,synopsis,periodo
1597,Upgrading and repairing PCs,Scott Mueller,1988,Non fiction,/works/OL65487W,Runaway best-selling PC hardware book of all t...,1970-1989
1598,The story of my life,Helen Keller,1903,Non fiction,/works/OL53604W,Helen Keller graduated cum laude from Radcliff...,1900-1949
1599,The Power of Now,Eckhart Tolle,1997,Non fiction,/works/OL5727686W,Eckhart Tolle has emerged as one of today's mo...,1990-1999

In [120]:
# DF original
# Una vez limpio y tratado el dataframe volvemos a generarlo en CSV
df_final.to_csv(
    "books_original.csv",
    index=False,
    encoding="utf-8",
    sep=",",
    quoting=csv.QUOTE_ALL,
    doublequote=True,
    quotechar='"',
    escapechar="\\",
    lineterminator="\n")
print("Filas:", len(df_final))
df_final.head(10)

Filas: 1600

,title,author,year,genre,openlibrary_work_key,synopsis,periodo
0,Alice's Adventures in Wonderland,Lewis Carroll,1865,Fantasy,/works/OL138052W,Alice's Adventures in Wonderland (commonly Ali...,1850-1899
1,The Wonderful Wizard of Oz,L. Frank Baum,1899,Fantasy,/works/OL18417W,"Over a century after its initial publication, ...",1850-1899
2,Treasure Island,Robert Louis Stevenson,1880,Fantasy,/works/OL24034W,Traditionally considered a coming-of-age story...,1850-1899
3,Gulliver's Travels,Jonathan Swift,1726,Fantasy,/works/OL20600W,A parody of traveler’s tales and a satire of h...,1700-1799
4,A Midsummer Night's Dream,William Shakespeare,1600,Fantasy,/works/OL259010W,One night two young couples run into an enchan...,1600-1699
5,The Prince,Niccolò Machiavelli,1515,Fantasy,/works/OL1089297W,The Prince (Italian: Il Principe [il ˈprintʃip...,1500-1599
6,Through the Looking-Glass,Lewis Carroll,1865,Fantasy,/works/OL151406W,"*Through the Looking-Glass, and What Alice Fou...",1850-1899
7,The Wind in the Willows,Kenneth Grahame,1908,Fantasy,/works/OL28570037W,"The adventures of four amiable animals, Rat, T...",1900-1949
8,Five Children and It,Edith Nesbit,1905,Fantasy,/works/OL99499W,Haven't you ever thought what you would wish f...,1900-1949
9,The Princess and the Goblin,George MacDonald,1872,Fantasy,/works/OL15449W,There was once a little princess whose father ...,1850-1899

In [121]:
# DF sin duplicados
# Una vez limpio y tratado el dataframe volvemos a generarlo en CSV
df_clean.to_csv(
    "books_clean.csv",
    index=False,
    encoding="utf-8",
    sep=",",
    quoting=csv.QUOTE_ALL,
    doublequote=True,
    quotechar='"',
    escapechar="\\",
    lineterminator="\n")
print("Filas:", len(df_clean))
df_clean.tail(10)

Filas: 1461

,title,author,year,genre,openlibrary_work_key,synopsis,periodo
1590,Las venas abiertas de América Latina,Eduardo Galeano,1971,Non fiction,/works/OL698173W,"Since its U.S. debut almost fifty years ago, t...",1970-1989
1591,"Behind the scenes. By Elizabeth Keckley. Or, T...",Elizabeth Keckley,1868,Non fiction,/works/OL4968216W,A former slave's intimate memoir of the Lincol...,1850-1899
1592,Personal Memoirs of U. S. Grant (2 volumes in 1),Ulysses S. Grant,1894,Non fiction,/works/OL1928235W,"Tracing his ancestry, Grant gives insight into...",1850-1899
1593,The history of England from the accession of J...,Thomas Babington Macaulay,1849,Non fiction,/works/OL8522726W,While instituting the English education system...,1800-1849
1594,The science of being great,Wallace D. Wattles,1911,Non fiction,/works/OL3792048W,"Newly rediscovered by fans of The Secret, the ...",1900-1949
1595,Domestic manners of the Americans,Frances Milton Trollope,1832,Non fiction,/works/OL2147971W,When Fanny Trollope set sail for America in 18...,1800-1849
1596,Les tragiques,Agrippa d' Aubigné,1800,Non fiction,/works/OL1496762W,None,1800-1849
1597,Upgrading and repairing PCs,Scott Mueller,1988,Non fiction,/works/OL65487W,Runaway best-selling PC hardware book of all t...,1970-1989
1598,The story of my life,Helen Keller,1903,Non fiction,/works/OL53604W,Helen Keller graduated cum laude from Radcliff...,1900-1949
1599,The Power of Now,Eckhart Tolle,1997,Non fiction,/works/OL5727686W,Eckhart Tolle has emerged as one of today's mo...,1990-1999

In [111]:
df_title_syn = df_clean[['title', 'synopsis']]
df_title_syn.head(2)

,title,synopsis
0,Alice's Adventures in Wonderland,Alice's Adventures in Wonderland (commonly Ali...
1,The Wonderful Wizard of Oz,"Over a century after its initial publication, ..."

In [122]:
df_title_syn.to_csv(
    "books_title_synopsis.csv",
    index=False,
    encoding="utf-8",
    sep=",",
    quoting=csv.QUOTE_ALL,
    doublequote=True,
    quotechar='"',
    escapechar="\\",
    lineterminator="\n")
print("Filas:", len(df_title_syn))
df_title_syn.head(10)

Filas: 1461

,title,synopsis
0,Alice's Adventures in Wonderland,Alice's Adventures in Wonderland (commonly Ali...
1,The Wonderful Wizard of Oz,"Over a century after its initial publication, ..."
2,Treasure Island,Traditionally considered a coming-of-age story...
3,Gulliver's Travels,A parody of traveler’s tales and a satire of h...
4,A Midsummer Night's Dream,One night two young couples run into an enchan...
5,The Prince,The Prince (Italian: Il Principe [il ˈprintʃip...
6,Through the Looking-Glass,"*Through the Looking-Glass, and What Alice Fou..."
7,The Wind in the Willows,"The adventures of four amiable animals, Rat, T..."
8,Five Children and It,Haven't you ever thought what you would wish f...
9,The Princess and the Goblin,There was once a little princess whose father ...

## Por hacer:
- [X] publishers eliminar
- [X] Cambiar géneros a inglés
- [X] Añadir años de publicación para los dos libros que están en año 0
- [X] Sacar sinopsis 
- [X] décadas: 
1400-1499, 
1500-1599, 
1600-1699, 
1700-1799, 
1800-1849, 
1850-1899, 
1900-1949, 
1950-1969, 
1970-1989, 
1990-1999, 
2000-2009, 
2010-2019, 
2020-2026

- [X] IRENE: csv titulo y sinopsis ('books_title_synopsis.csv')

- [X] CLARA: csv sin duplicados pero con los años ajustados y demás, csv con duplicados ('books_original.csv' -> con duplicados y 'books_clean.csv' -> sin duplicados)